### ISSUE TITLE
Khi hover chiều cao bị thay đôi, khối đầu tiên đường kẻ khi hover khác với các khối khác

### ISSUE THREAD

**Issue by vuthaihoc** [NaTaShaRMN/fontend-practice#3]
![image](https://user-images.githubusercontent.com/2509658/62189221-a2d85c00-b398-11e9-8e04-308ca3123ede.png)

**Comment by nguyenanhtuan21** [comment]
Vâng ạ . Nãy quên thử dùng cách khác cho cái đấy mà chưa chỉnh lại :))
